snowflakedb/snowpark-checkpoints

pyproject.toml
recipe/meta.yaml
snowpark-checkpoints-collectors/pyproject.toml
snowpark-checkpoints-collectors/recipe/meta.yaml
snowpark-checkpoints-validators/pyproject.toml
snowpark-checkpoints-validators/recipe/meta.yaml

JIRA: SNOW-1797964
- If this change does not meet the bar for low risk without security requirements (as confirmed by the peer reviewers of this pull request) then a [formal Risk Assessment](https://snowflakecomputing.atlassian.net/wiki/spaces/ESP/pages/659818607/Risk+Assessment) must be completed. Please note that a formal Risk Assessment will require you to spend extra time performing a security review for this change. Please account for this extra time earlier rather than later to avoid unnecessary delays in the release process.

SNOW-1797964: Fix snowflake-connector-python

---

__version__.py
recipe/meta.yaml
snowpark-checkpoints-collectors/recipe/meta.yaml
snowpark-checkpoints-collectors/src/snowflake/snowpark_checkpoints_collector/__version__.py
snowpark-checkpoints-configuration/recipe/meta.yaml
snowpark-checkpoints-configuration/src/snowflake/snowpark_checkpoints_configuration/__version__.py
snowpark-checkpoints-hypothesis/recipe/meta.yaml
snowpark-checkpoints-hypothesis/src/snowflake/hypothesis_snowpark/__version__.py
snowpark-checkpoints-validators/recipe/meta.yaml
snowpark-checkpoints-validators/src/snowflake/snowpark_checkpoints/__version__.py

JIRA: SNOW-1797964
- New Release PuPr
- If this change does not meet the bar for low risk without security requirements (as confirmed by the peer reviewers of this pull request) then a [formal Risk Assessment](https://snowflakecomputing.atlassian.net/wiki/spaces/ESP/pages/659818607/Risk+Assessment) must be completed. Please note that a formal Risk Assessment will require you to spend extra time performing a security review for this change. Please account for this extra time earlier rather than later to avoid unnecessary delays in the release process.

SNOW-1797964: Bump version to 0.1.2

---

.github/workflows/collectors-use-tests_all.yml
.github/workflows/configuration-use-tests_all.yml
.github/workflows/hypothesis-use-tests_all.yml
.github/workflows/snowpark-checkpoints-all-tests-w-coverage.yml
.github/workflows/snowpark-checkpoints-all-tests.yml
.github/workflows/validators-use-tests_all.yml
README.md
recipe/meta.yaml
snowpark-checkpoints-collectors/pyproject.toml
snowpark-checkpoints-configuration/pyproject.toml
snowpark-checkpoints-configuration/recipe/meta.yaml
snowpark-checkpoints-hypothesis/pyproject.toml
snowpark-checkpoints-validators/pyproject.toml

JIRA: SNOW-1797964
More Info:
[Dashboard](https://app.codecov.io/gh/snowflakedb/snowpark-checkpoints/tree/support%2Fupload-coverage/)
[Build Logs](https://github.com/snowflakedb/snowpark-checkpoints/actions/runs/13144287777/job/36679911918)
- If this change does not meet the bar for low risk without security requirements (as confirmed by the peer reviewers of this pull request) then a [formal Risk Assessment](https://snowflakecomputing.atlassian.net/wiki/spaces/ESP/pages/659818607/Risk+Assessment) must be completed. Please note that a formal Risk Assessment …

SNOW-1797964: Set CodeCov Tasks

---

__version__.py
recipe/meta.yaml
snowpark-checkpoints-collectors/recipe/meta.yaml
snowpark-checkpoints-collectors/src/snowflake/snowpark_checkpoints_collector/__version__.py
snowpark-checkpoints-configuration/recipe/meta.yaml
snowpark-checkpoints-configuration/src/snowflake/snowpark_checkpoints_configuration/__version__.py
snowpark-checkpoints-hypothesis/recipe/meta.yaml
snowpark-checkpoints-hypothesis/src/snowflake/hypothesis_snowpark/__version__.py
snowpark-checkpoints-validators/recipe/meta.yaml
snowpark-checkpoints-validators/src/snowflake/snowpark_checkpoints/__version__.py

JIRA: SNOW-1797964
- If this change does not meet the bar for low risk without security requirements (as confirmed by the peer reviewers of this pull request) then a [formal Risk Assessment](https://snowflakecomputing.atlassian.net/wiki/spaces/ESP/pages/659818607/Risk+Assessment) must be completed. Please note that a formal Risk Assessment will require you to spend extra time performing a security review for this change. Please account for this extra time earlier rather than later to avoid unnecessary delays in the release process.

SNOW-1797964: Bump version to 0.1.3

---

snowpark-checkpoints-configuration/src/snowflake/snowpark_checkpoints_configuration/__init__.py
snowpark-checkpoints-configuration/src/snowflake/snowpark_checkpoints_configuration/checkpoint_metadata.py
snowpark-checkpoints-configuration/src/snowflake/snowpark_checkpoints_configuration/model/checkpoints.py
snowpark-checkpoints-configuration/test/unit/test_checkpoint_metadata.py
snowpark-checkpoints-configuration/test/unit/test_checkpoint_name_utils.py
snowpark-checkpoints-configuration/test/unit/test_checkpoints.py
snowpark-checkpoints-configuration/test/unit/test_logger.py

JIRA: [SNOW-1932731](https://snowflakecomputing.atlassian.net/browse/SNOW-1932731)
This pull request introduces logging messages across multiple modules of the `snowpark-checkpoints-configuration` package. This messages aim to enhance the debugging and monitoring capabilities of the package.
* Added testing to validate the overall logging mechanism.
* Added testing to validate important log messages.
- If this change does not meet the bar for low risk without security requirements (as confirmed by the peer reviewers of this pull request) then a [formal Risk …

SNOW-1932731: Add logging messages to snowpark-checkpoints-configuration

---

.github/workflows/collectors-use-tests_all.yml
.github/workflows/configuration-use-tests_all.yml
.github/workflows/hypothesis-use-tests_all.yml
.github/workflows/snowpark-checkpoints-pr-lint.yml
.github/workflows/validators-use-tests_all.yml

JIRA: [SNOW-1797964](https://snowflakecomputing.atlassian.net/browse/SNOW-1797964)
- If this change does not meet the bar for low risk without security requirements (as confirmed by the peer reviewers of this pull request) then a [formal Risk Assessment](https://snowflakecomputing.atlassian.net/wiki/spaces/ESP/pages/659818607/Risk+Assessment) must be completed. Please note that a formal Risk Assessment will require you to spend extra time performing a security review for this change. Please account for this extra time earlier rather than later to avoid …

SNOW-1797964: Upgrade python 3.9 matrix

---

.github/scripts/py_create_requirements.py
README.md
docs/source/conf.py
pyproject.toml
recipe/meta.yaml
snowpark-checkpoints-collectors/README.md
snowpark-checkpoints-collectors/pyproject.toml
snowpark-checkpoints-collectors/recipe/meta.yaml
snowpark-checkpoints-configuration/pyproject.toml
snowpark-checkpoints-configuration/recipe/meta.yaml
snowpark-checkpoints-hypothesis/pyproject.toml
snowpark-checkpoints-hypothesis/recipe/meta.yaml
snowpark-checkpoints-validators/README.md
snowpark-checkpoints-validators/pyproject.toml
snowpark-checkpoints-validators/recipe/meta.yaml
snowpark-checkpoints-validators/src/snowflake/snowpark_checkpoints/checkpoint.py

JIRA: [SNOW-1944918](https://snowflakecomputing.atlassian.net/browse/SNOW-1944918)
Change the pyspark dependency to make it optional.
- If this change does not meet the bar for low risk without security requirements (as confirmed by the peer reviewers of this pull request) then a [formal Risk Assessment](https://snowflakecomputing.atlassian.net/wiki/spaces/ESP/pages/659818607/Risk+Assessment) must be completed. Please note that a formal Risk Assessment will require you to spend extra time performing a security review for this change. Please account for this …

SNOW-1944918 Update pyspark project dependencie

---

__version__.py
recipe/meta.yaml
snowpark-checkpoints-collectors/recipe/meta.yaml
snowpark-checkpoints-collectors/src/snowflake/snowpark_checkpoints_collector/__version__.py
snowpark-checkpoints-configuration/recipe/meta.yaml
snowpark-checkpoints-configuration/src/snowflake/snowpark_checkpoints_configuration/__version__.py
snowpark-checkpoints-hypothesis/recipe/meta.yaml
snowpark-checkpoints-hypothesis/src/snowflake/hypothesis_snowpark/__version__.py
snowpark-checkpoints-validators/recipe/meta.yaml
snowpark-checkpoints-validators/src/snowflake/snowpark_checkpoints/__version__.py

JIRA: [SNOW-1797964](https://snowflakecomputing.atlassian.net/browse/SNOW-1797964)
- If this change does not meet the bar for low risk without security requirements (as confirmed by the peer reviewers of this pull request) then a [formal Risk Assessment](https://snowflakecomputing.atlassian.net/wiki/spaces/ESP/pages/659818607/Risk+Assessment) must be completed. Please note that a formal Risk Assessment will require you to spend extra time performing a security review for this change. Please account for this extra time earlier rather than later …

SNOW-1797964: Bump version to 0.1.4

---

snowpark-checkpoints-validators/test/unit/test_validation_result_metadata.py

JIRA: [SNOW-1944918](https://snowflakecomputing.atlassian.net/browse/SNOW-1944918)
Add two unit test for _validate function
- If this change does not meet the bar for low risk without security requirements (as confirmed by the peer reviewers of this pull request) then a [formal Risk Assessment](https://snowflakecomputing.atlassian.net/wiki/spaces/ESP/pages/659818607/Risk+Assessment) must be completed. Please note that a formal Risk Assessment will require you to spend extra time performing a security review for this change. Please account for this extra time …

SNOW-1944918 Add unit test for _validate function

---

__version__.py
recipe/meta.yaml
snowpark-checkpoints-collectors/recipe/meta.yaml
snowpark-checkpoints-collectors/src/snowflake/snowpark_checkpoints_collector/__version__.py
snowpark-checkpoints-configuration/recipe/meta.yaml
snowpark-checkpoints-configuration/src/snowflake/snowpark_checkpoints_configuration/__version__.py
snowpark-checkpoints-hypothesis/recipe/meta.yaml
snowpark-checkpoints-hypothesis/src/snowflake/hypothesis_snowpark/__version__.py
snowpark-checkpoints-validators/recipe/meta.yaml
snowpark-checkpoints-validators/src/snowflake/snowpark_checkpoints/__version__.py

JIRA: [SNOW-2002392](https://snowflakecomputing.atlassian.net/browse/SNOW-2002392)
- If this change does not meet the bar for low risk without security requirements (as confirmed by the peer reviewers of this pull request) then a [formal Risk Assessment](https://snowflakecomputing.atlassian.net/wiki/spaces/ESP/pages/659818607/Risk+Assessment) must be completed. Please note that a formal Risk Assessment will require you to spend extra time performing a security review for this change. Please account for this extra time earlier rather than later …

SNOW-2002392: Bump version to 0.2.0

---

snowpark-checkpoints-collectors/src/snowflake/snowpark_checkpoints_collector/summary_stats_collector.py
snowpark-checkpoints-collectors/src/snowflake/snowpark_checkpoints_collector/utils/checkpoint_name_utils.py
snowpark-checkpoints-collectors/test/integ/test_checkpoint_name.py
snowpark-checkpoints-collectors/test/unit/test_checkpoint_name_utils.py
snowpark-checkpoints-configuration/src/snowflake/snowpark_checkpoints_configuration/checkpoint_name_utils.py
snowpark-checkpoints-configuration/src/snowflake/snowpark_checkpoints_configuration/model/checkpoints.py
snowpark-checkpoints-configuration/test/unit/test_checkpoint_name_utils.py
snowpark-checkpoints-validators/src/snowflake/snowpark_checkpoints/utils/utils_checks.py

JIRA: [SNOW-2024689](https://snowflakecomputing.atlassian.net/browse/SNOW-2024689)
Checkpoints did not accept $ sings as part of a checkpoint name.
- If this change does not meet the bar for low risk without security requirements (as confirmed by the peer reviewers of this pull request) then a [formal Risk Assessment](https://snowflakecomputing.atlassian.net/wiki/spaces/ESP/pages/659818607/Risk+Assessment) must be completed. Please note that a formal Risk Assessment will require you to spend extra time performing a security review for this change. Please …

SNOW-2024689: Checkpoint names with dollar sign are accepted

---

__version__.py
recipe/meta.yaml
snowpark-checkpoints-collectors/recipe/meta.yaml
snowpark-checkpoints-collectors/src/snowflake/snowpark_checkpoints_collector/__version__.py
snowpark-checkpoints-configuration/recipe/meta.yaml
snowpark-checkpoints-configuration/src/snowflake/snowpark_checkpoints_configuration/__version__.py
snowpark-checkpoints-hypothesis/pyproject.toml
snowpark-checkpoints-hypothesis/recipe/meta.yaml
snowpark-checkpoints-hypothesis/src/snowflake/hypothesis_snowpark/__version__.py
snowpark-checkpoints-validators/recipe/meta.yaml
snowpark-checkpoints-validators/src/snowflake/snowpark_checkpoints/__version__.py

JIRA: [SNOW-1797964](https://snowflakecomputing.atlassian.net/browse/SNOW-1797964)
- If this change does not meet the bar for low risk without security requirements (as confirmed by the peer reviewers of this pull request) then a [formal Risk Assessment](https://snowflakecomputing.atlassian.net/wiki/spaces/ESP/pages/659818607/Risk+Assessment) must be completed. Please note that a formal Risk Assessment will require you to spend extra time performing a security review for this change. Please account for this extra time earlier rather than later …

SNOW-1797964: Bump version to 0.2.1

---

pyproject.toml
recipe/meta.yaml
snowpark-checkpoints-validators/pyproject.toml
snowpark-checkpoints-validators/recipe/meta.yaml

JIRA: [SNOW-2029024](https://snowflakecomputing.atlassian.net/browse/SNOW-2029024)
Update pydantic dependency in Snowpark-Checkpoints-Validators to version 2.0 or higher.
- If this change does not meet the bar for low risk without security requirements (as confirmed by the peer reviewers of this pull request) then a [formal Risk Assessment](https://snowflakecomputing.atlassian.net/wiki/spaces/ESP/pages/659818607/Risk+Assessment) must be completed. Please note that a formal Risk Assessment will require you to spend extra time performing a security review for …

SNOW-2029024 Update pydantic dependencie in Snowpark-Checkpoints-Validators

---

snowpark-checkpoints-collectors/src/snowflake/snowpark_checkpoints_collector/utils/extra_config.py
snowpark-checkpoints-collectors/test/unit/test_extra_config.py
snowpark-checkpoints-configuration/src/snowflake/snowpark_checkpoints_configuration/checkpoint_metadata.py
snowpark-checkpoints-configuration/src/snowflake/snowpark_checkpoints_configuration/io_utils/__init__.py
snowpark-checkpoints-configuration/src/snowflake/snowpark_checkpoints_configuration/io_utils/io_default_strategy.py
snowpark-checkpoints-configuration/src/snowflake/snowpark_checkpoints_configuration/io_utils/io_env_strategy.py
snowpark-checkpoints-configuration/src/snowflake/snowpark_checkpoints_configuration/io_utils/io_file_manager.py
snowpark-checkpoints-configuration/test/unit/io_utils/test_default_strategy.py
snowpark-checkpoints-validators/src/snowflake/snowpark_checkpoints/utils/extra_config.py
snowpark-checkpoints-validators/test/unit/test_extra_config.py

JIRA: [SNOW-2057865](https://snowflakecomputing.atlassian.net/browse/SNOW-2057865)
Implement an I/O strategy pattern in the Snowpark-Checkpoints-Configuration to provide a way to change I/O behaviors at runtime depending on the execution environment.
Unit testing, integration testing,
- If this change does not meet the bar for low risk without security requirements (as confirmed by the peer reviewers of this pull request) then a [formal Risk Assessment](https://snowflakecomputing.atlassian.net/wiki/spaces/ESP/pages/659818607/Risk+Assessment) must be completed. …

SNOW-2057865 Implement Strategy Pattern for I/O in Snowpark-Checkpoints-Configuration 

---

snowpark-checkpoints-collectors/src/snowflake/snowpark_checkpoints_collector/io_utils/io_default_strategy.py
snowpark-checkpoints-collectors/src/snowflake/snowpark_checkpoints_collector/io_utils/io_env_strategy.py
snowpark-checkpoints-collectors/src/snowflake/snowpark_checkpoints_collector/io_utils/io_file_manager.py
snowpark-checkpoints-collectors/src/snowflake/snowpark_checkpoints_collector/utils/telemetry.py
snowpark-checkpoints-collectors/test/integ/test_collect_df_mode_1.py
snowpark-checkpoints-collectors/test/integ/test_collect_df_mode_2.py
snowpark-checkpoints-collectors/test/unit/io_utils/test_default_strategy.py
snowpark-checkpoints-hypothesis/src/snowflake/hypothesis_snowpark/io_utils/io_default_strategy.py
snowpark-checkpoints-hypothesis/src/snowflake/hypothesis_snowpark/io_utils/io_env_strategy.py
snowpark-checkpoints-hypothesis/src/snowflake/hypothesis_snowpark/io_utils/io_file_manager.py
snowpark-checkpoints-hypothesis/src/snowflake/hypothesis_snowpark/telemetry/telemetry.py
snowpark-checkpoints-hypothesis/test/integ/test_io_strategies.py
snowpark-checkpoints-hypothesis/test/unit/io_utils/test_default_strategy.py
snowpark-checkpoints-validators/src/snowflake/snowpark_checkpoints/io_utils/io_default_strategy.py
snowpark-checkpoints-validators/src/snowflake/snowpark_checkpoints/io_utils/io_env_strategy.py
snowpark-checkpoints-validators/src/snowflake/snowpark_checkpoints/io_utils/io_file_manager.py
snowpark-checkpoints-validators/src/snowflake/snowpark_checkpoints/utils/telemetry.py
snowpark-checkpoints-validators/test/integ/test_parquet.py
snowpark-checkpoints-validators/test/unit/io_utils/test_default_strategy.py
snowpark-checkpoints-validators/test/unit/test_telemetry.py

JIRA: [SNOW-2057870](https://snowflakecomputing.atlassian.net/browse/SNOW-2057870)
- If this change does not meet the bar for low risk without security requirements (as confirmed by the peer reviewers of this pull request) then a [formal Risk Assessment](https://snowflakecomputing.atlassian.net/wiki/spaces/ESP/pages/659818607/Risk+Assessment) must be completed. Please note that a formal Risk Assessment will require you to spend extra time performing a security review for this change. Please account for this extra time earlier rather than later to avoid …

SNOW-2057870 Fix snowpark-checkpoints telemetry behavior for Databricks

---

pyproject.toml
snowpark-checkpoints-collectors/pyproject.toml
snowpark-checkpoints-configuration/pyproject.toml
snowpark-checkpoints-hypothesis/pyproject.toml
snowpark-checkpoints-testing/pyproject.toml
snowpark-checkpoints-validators/pyproject.toml

JIRA: [SNOW-2069546](https://snowflakecomputing.atlassian.net/browse/SNOW-2069546)
Snowflake has been experiencing issues with the "certificate is revoked" error during CBS ingestion, impacting pipelines in production
Pinning the certifi dependency to a specific version (certifi==2025.1.31) when installing Python environment dependencies.
All Unit-Test are working 
- If this change does not meet the bar for low risk without security requirements (as confirmed by the peer reviewers of this pull request) then a [formal Risk …

SNOW-2069546: Fix Snowflake Certificates

---

__version__.py
recipe/meta.yaml
snowpark-checkpoints-collectors/recipe/meta.yaml
snowpark-checkpoints-collectors/src/snowflake/snowpark_checkpoints_collector/__version__.py
snowpark-checkpoints-configuration/recipe/meta.yaml
snowpark-checkpoints-configuration/src/snowflake/snowpark_checkpoints_configuration/__version__.py
snowpark-checkpoints-hypothesis/recipe/meta.yaml
snowpark-checkpoints-hypothesis/src/snowflake/hypothesis_snowpark/__version__.py
snowpark-checkpoints-validators/recipe/meta.yaml
snowpark-checkpoints-validators/src/snowflake/snowpark_checkpoints/__version__.py

JIRA: [SNOW-2071998](https://snowflakecomputing.atlassian.net/browse/SNOW-2071998)
- If this change does not meet the bar for low risk without security requirements (as confirmed by the peer reviewers of this pull request) then a [formal Risk Assessment](https://snowflakecomputing.atlassian.net/wiki/spaces/ESP/pages/659818607/Risk+Assessment) must be completed. Please note that a formal Risk Assessment will require you to spend extra time performing a security review for this change. Please account for this extra time earlier rather than later …

SNOW-2071998: Bump version to 0.3.0

---

docs/source/snowpark-checkpoints-collectors/modules.rst
docs/source/snowpark-checkpoints-configuration/modules.rst
docs/source/snowpark-checkpoints-hypothesis/modules.rst
docs/source/snowpark-checkpoints-validators/modules.rst

JIRA: [SNOW-1944478](https://snowflakecomputing.atlassian.net/browse/SNOW-1944478)
This pull request updates the documentation to include the `io_utils` module in various Snowpark-related sections. The changes ensure that the new `io_utils` module is properly referenced across the documentation.
Documentation updates:
* Added `snowflake.snowpark_checkpoints_collector.io_utils` to the `snowflake.snowpark_checkpoints_collector` section in `docs/source/snowpark-checkpoints-collectors/modules.rst`.
* Added `snowflake.snowpark_checkpoints_configuration.io_utils` to the `snowflake.snowpark_checkpoints_configuration` section in `docs/source/snowpark-checkpoints-configuration/modules.rst`.
* Added `snowflake.hypothesis_snowpark.io_utils` to the `snowflake.hypothesis_snowpark` section in …

SNOW-1944478 Add io_utils files into the API docs

---

snowpark-checkpoints-collectors/src/snowflake/snowpark_checkpoints_collector/utils/file_utils.py
snowpark-checkpoints-collectors/test/unit/test_file_utils.py

JIRA: [SNOW-2072076](https://snowflakecomputing.atlassian.net/browse/SNOW-2072076)
- Change the mechanism to retrieve the filename where a collector was defined to save it into the results file. Now, a batch of 7 frames is extracted from the stack to find the call of the collector and extract its path.
- Update testing dependencies to mock the calling to the method.
- If this change does not meet the bar for low risk without security requirements (as confirmed by the peer reviewers of this pull request) then a [formal Risk …

SNOW-2072076: Filename of checkpoint extracted from StackTrace does not match

---

__version__.py
recipe/meta.yaml
snowpark-checkpoints-collectors/recipe/meta.yaml
snowpark-checkpoints-collectors/src/snowflake/snowpark_checkpoints_collector/__version__.py
snowpark-checkpoints-configuration/recipe/meta.yaml
snowpark-checkpoints-configuration/src/snowflake/snowpark_checkpoints_configuration/__version__.py
snowpark-checkpoints-hypothesis/recipe/meta.yaml
snowpark-checkpoints-hypothesis/src/snowflake/hypothesis_snowpark/__version__.py
snowpark-checkpoints-validators/recipe/meta.yaml
snowpark-checkpoints-validators/src/snowflake/snowpark_checkpoints/__version__.py

JIRA: [SNOW-2097723](https://snowflakecomputing.atlassian.net/browse/SNOW-2097723)
- If this change does not meet the bar for low risk without security requirements (as confirmed by the peer reviewers of this pull request) then a [formal Risk Assessment](https://snowflakecomputing.atlassian.net/wiki/spaces/ESP/pages/659818607/Risk+Assessment) must be completed. Please note that a formal Risk Assessment will require you to spend extra time performing a security review for this change. Please account for this extra time earlier rather than later to avoid …

SNOW-2097723: Bump version to 0.3.1

---

snowpark-checkpoints-validators/src/snowflake/snowpark_checkpoints/__init__.py
snowpark-checkpoints-validators/test/unit/test_utils_checks.py

JIRA: [SNOW-2100996](https://snowflakecomputing.atlassian.net/browse/SNOW-2100996)
Fix error when importing `xvalidate_dataframe_checkpoint` from `snowflake.snowpark_checkpoints`
- Add a unit test to verify if the import of the method `xvalidate_dataframe_checkpoint` is valid or not.
- If this change does not meet the bar for low risk without security requirements (as confirmed by the peer reviewers of this pull request) then a [formal Risk Assessment](https://snowflakecomputing.atlassian.net/wiki/spaces/ESP/pages/659818607/Risk+Assessment) must be completed. …

SNOW-2100996: Fix invalid import for 'xvalidate_dataframe_checkpoint'

---

__version__.py
recipe/meta.yaml
snowpark-checkpoints-collectors/recipe/meta.yaml
snowpark-checkpoints-collectors/src/snowflake/snowpark_checkpoints_collector/__version__.py
snowpark-checkpoints-configuration/recipe/meta.yaml
snowpark-checkpoints-configuration/src/snowflake/snowpark_checkpoints_configuration/__version__.py
snowpark-checkpoints-hypothesis/recipe/meta.yaml
snowpark-checkpoints-hypothesis/src/snowflake/hypothesis_snowpark/__version__.py
snowpark-checkpoints-validators/recipe/meta.yaml
snowpark-checkpoints-validators/src/snowflake/snowpark_checkpoints/__version__.py

JIRA: [SNOW-2101346](https://snowflakecomputing.atlassian.net/browse/SNOW-2101346)
- If this change does not meet the bar for low risk without security requirements (as confirmed by the peer reviewers of this pull request) then a [formal Risk Assessment](https://snowflakecomputing.atlassian.net/wiki/spaces/ESP/pages/659818607/Risk+Assessment) must be completed. Please note that a formal Risk Assessment will require you to spend extra time performing a security review for this change. Please account for this extra time earlier rather than later to avoid …

SNOW-2101346: Bump version to 0.3.2

---

__version__.py
recipe/meta.yaml
snowpark-checkpoints-collectors/recipe/meta.yaml
snowpark-checkpoints-collectors/src/snowflake/snowpark_checkpoints_collector/__version__.py
snowpark-checkpoints-configuration/recipe/meta.yaml
snowpark-checkpoints-configuration/src/snowflake/snowpark_checkpoints_configuration/__version__.py
snowpark-checkpoints-hypothesis/recipe/meta.yaml
snowpark-checkpoints-hypothesis/src/snowflake/hypothesis_snowpark/__version__.py
snowpark-checkpoints-validators/recipe/meta.yaml
snowpark-checkpoints-validators/src/snowflake/snowpark_checkpoints/__version__.py

✨ This commit updates version files after a successful release
📦 Version bumped to: 0.4.0
🤖 Auto-generated by release workflow
Co-authored-by: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
JIRA: [SNOW-2182138](https://snowflakecomputing.atlassian.net/browse/SNOW-2182138)
- If this change does not meet the bar for low risk without security requirements (as confirmed by the peer reviewers of this pull request) then a [formal Risk Assessment](https://snowflakecomputing.atlassian.net/wiki/spaces/ESP/pages/659818607/Risk+Assessment) must be …

Release v0.4.0: Bump version files
